services:
  productsapi:
    image: ${DOCKER_REGISTRY-}productsapi
    build:
      context: .
      dockerfile: ProductsApi/Dockerfile
    ports:
      - 5000:8080
      - 5001:8081

  postgres:
     image: postgres:17
     container_name: postgres
     environment:
        - POSTGRES_DB=products
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
     volumes:
        - ./.containers/db:/var/lib/postgresql/data
     ports:
        - 5432:5432