### Stage 1: Build the angular application
FROM node:18-alpine AS build
# Install bash, git, openssh and ca-certificates
RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh ca-certificates && \
    rm -rf /var/cache/apk/*

# install pnpm
RUN npm install -g pnpm

# create app directory
WORKDIR /usr/src/app
COPY customer-app .

# install app dependencies
RUN pnpm install

# Arguments for build
ARG ng_build_configuration
ARG theme_value=defaultTheme

# build the angular application
RUN pnpm ng build --configuration $ng_build_configuration --theme $theme_value

### Stage 2: Serve the application with nginx
FROM nginx:1.23.4-alpine
COPY --from=build /usr/src/app/dist/customer-app/browser /usr/share/nginx/html
COPY nginx_angular.conf /etc/nginx/conf.d/default.conf
CMD ["/bin/sh", "-c", "envsubst < /usr/share/nginx/html/assets/env.template.js > /usr/share/nginx/html/assets/env.js && exec nginx -g 'daemon off;'"]

